import{S as g,a as h,i as f}from"./assets/vendor-527658dd.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const b=document.querySelector(".form"),d=document.querySelector(".gallery"),a=document.querySelector(".loader"),s=document.querySelector(".load-more");let y=1,u="",p=0,c=0;a.style.display="none";s.style.display="none";let L=new g(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"});b.addEventListener("submit",w);s.addEventListener("click",S);async function w(r){r.preventDefault(),u=document.querySelector("input").value.trim(),u&&(d.innerHTML="",a.style.display="inline-block",y=1,await m(),s.style.display="inline-block")}async function m(){try{const r=await h.get("https://pixabay.com/api/",{params:{key:"42110229-d56f9063956695e15527c98fc",q:u,image_type:"photo",orientation:"horizontal",safesearch:"true",page:y,per_page:15}});p=r.data.totalHits,v(r.data.hits)}catch(r){console.error(r),f.error({message:"Failed to fetch images. Please try again later."})}finally{a.style.display="none"}}function v(r){if(r.length===0){f.warning({message:"No images found. Please try a different search query."}),s.style.display="none";return}const n=r.map(o=>`<li class="gallery-item">
          <a class="gallery-link" href="${o.largeImageURL}">
            <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <div class="img-info">
            <p>Likes: ${o.likes}</p>
            <p>Views: ${o.views}</p>
            <p>Comments: ${o.comments}</p>
            <p>Downloads: ${o.downloads}</p>
          </div>
        </li>`).join("");d.insertAdjacentHTML("beforeend",n),L.refresh(),y++,c===0&&(c=document.querySelector(".gallery-item").getBoundingClientRect().height),window.scrollBy({top:c*2,behavior:"smooth"}),p<=d.children.length&&(s.style.display="none")}async function S(){a.style.display="inline-block",await m()}
//# sourceMappingURL=commonHelpers.js.map
